name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  build_and_push:
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
    - name: Login to docker
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u shvmedia --password-stdin
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t shvmedia/ls-2022-10-19:${GITHUB_REF:11} -f Dockerfile .
    - name: Push image to docker
      run: docker push shvmedia/ls-2022-10-19:${GITHUB_REF:11}
